#!/bin/bash
build() {
  add_binary /usr/bin/ykchalresp
  add_binary /usr/bin/sha256sum
  add_binary /usr/bin/openssl
  add_full_dir /usr/lib/openssl
  add_binary /usr/bin/xxd
  add_binary /usr/bin/diff
  add_binary /usr/bin/find
  add_binary /usr/bin/timeout
  add_file /etc/initcpio/hooks/integrity_check_script /usr/local/bin/integrity-check.sh
  add_file /etc/boot_integrity/boot_token.enc
  add_file /etc/boot_integrity/boot_hash
  add_file /etc/boot_integrity/integrity_hash
  add_file /etc/boot_integrity/salt.txt
  add_file /etc/boot_integrity/challenge
  add_runscript
}

help() {
  cat <<HELPOF
  This hook performs a boot integrity check using a Yubikey.
HELPOF
}
